version: '3.8'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "8000:8000/udp"
      - "8001:8001/udp"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml