@auth_HostAddress = http://localhost:5260


# Login Request
POST {{auth_HostAddress}}/login
Content-Type: application/json

{
  "username": "streamer",
  "password": "securepass"
}

# Auth Request
POST {{auth_HostAddress}}/auth
Content-Type: application/json

{
  "user": "streamer",
  "password": "securepass",
  "path": "stream/path",
  "protocol": "whip",
  "query": "jwt=your_jwt_token"
}