@auth_HostAddress = http://localhost:5260


# Login Request
POST {{auth_HostAddress}}/auth
Content-Type: application/json

{
  "username": "streamer",
  "password": "securepass"
}

GET {{auth_HostAddress}}/jwks.json