# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
         
    - name: Restore dependencies for Auth project
      working-directory: ./mediamtx/auth
      run: dotnet restore ./auth.csproj
    - name: Build
      run: dotnet build ./mediamtx/auth/auth.csproj --no-restore
    - name: Test
      run: dotnet test ./mediamtx/auth/auth.csproj --no-build --verbosity normal

    - name: Restore dependencies for Webhook project
      working-directory: ./mediamtx/webhook
      run: dotnet restore ./webhook.csproj
    - name: Build
      run: dotnet build ./mediamtx/webhook/webhook.csproj --no-restore
    - name: Test
      run: dotnet test ./mediamtx/webhook/webhook.csproj --no-build --verbosity normal
